#pragma once
#define NETWORK_PORT	20000

#define dfRANGE_MOVE_TOP	0
#define dfRANGE_MOVE_LEFT	0
#define dfRANGE_MOVE_RIGHT	6400
#define dfRANGE_MOVE_BOTTOM	6400

#define MAP_X_SIZE 6400
#define MAP_Y_SIZE 6400

#define MAX_HP 100

#define MOVE_TICK_X ((SHORT)3)
#define MOVE_TICK_Y ((SHORT)2)

#define dfATTACK1_RANGE_X   80
#define dfATTACK2_RANGE_X   90
#define dfATTACK3_RANGE_X   100
#define dfATTACK1_RANGE_Y   10
#define dfATTACK2_RANGE_Y   10
#define dfATTACK3_RANGE_Y   20
#define ATTACK_RANGE_DEBUG	1

#define ATTACK1_DAMAGE	1
#define ATTACK2_DAMAGE	2
#define ATTACK3_DAMAGE	3

#define DEADRECKONING_RANGE 50

enum TAG_ACTION
{
	ACTION_MOVE_LL = 0,
	ACTION_MOVE_LU,
	ACTION_MOVE_UU,
	ACTION_MOVE_RU,
	ACTION_MOVE_RR,
	ACTION_MOVE_RD,
	ACTION_MOVE_DD,
	ACTION_MOVE_LD,
	ATTACK_TYPE_1 = 8,
	ATTACK_TYPE_2,
	ATTACK_TYPE_3,
	STAND = 11,
	NONE = 12
};